### ISSUE TITLE
question about 2nd level covariate

### ISSUE THREAD

**Issue by munoztd0** [JoramSoch/MACS#6]
Hello, 

First, this is more of a question than an issue.
I was wondering if there was a way to compare a model using a first-level modulator (as in a rating for each trial) VS a model using a second level ( as in an overall rating index) covariate using MACS ?

Thanks in advance,

David

**Comment by JoramSoch** [comment]
@munoztd0:
1) Bayesian model selection has an *identical data requirement*. This means, it only makes sense to compare different models operating on the *same* data (because it's trivial that different models operating on different data perform differently). As first-level models and a second-level model are operating on *different* data (measured BOLD signals vs. first-level parameter estimates), you **cannot** compare them to each other.
2) What you **can** do (I actually added this functionality not very long ago) is to compare different *second-level models*, e.g. one having a regressor for overall rating index vs. one not having it.
3) Similarly, you **can** of course also always run a comparison between two *first-level models*, e.g. one having the parametric modulator coding trial-wise ratings vs. one not having it.
Hope this helps!

**Comment by munoztd0** [comment]
Hey, thanks for your clear and detailed response!
