### ISSUE TITLE
Questions about 'MA: inspect goodness of fit' module

### ISSUE THREAD

**Issue by FaxinZ** [JoramSoch/MACS#7]
Hi, Thanks for this useful toolbox! 

I'm currently using 'MA: inspect goodness of fit' module to assess R2 of two GLM models. In detail, the first model have less regressors than the second one; but in some voxels, the R2 of the first model is larger. I would like to know if this is reasonable or anything I can do to improve it?
And by the way, the model I build is in a multi-session setup, maybe this is an influencing factor?

Thanks in advance,
Faxin

**Comment by JoramSoch** [comment]
Dear Faxin,

thanks for your question.

> In detail, the first model have less regressors than the second one; but in some voxels, the R2 of the first model is larger. I would like to know if this is reasonable or anything I can do to improve it?

It depends. Is the first model nested (i.e. contained) within the second model? If yes, then my answer would be no, this shouldn't be possible, because adding (rather than replacing) regressors always increases R^2 (but not necessarily R^2_adj!). If m1 is not nested within m2 (e.g. because using completely different regressors), then yes, this could be possible, if the fewer regressors of m1 have larger explanatory power than the more regressors of m2.

> And by the way, the model I build is in a multi-session setup, maybe this is an influencing factor?

That could be possible, but is highly unlikely (because I can't imagine how it should cause the phenomonen you are seeing). [Here's an explanation](https://github.com/JoramSoch/MACS/blob/master/MA_inspect_GoF.m#L51) how multi-session GLMs are handled by "inspect goodness of fit":

> % For several reasons, the implicit baseline is subtracted from the
% (whitened and filtered) measured as well as from the predicted signal.
% First of all, the absolute value of the baseline is meaningless and
% arbitrary. Second, the baseline differs across sessions which can make it
% hard to inspect the signal when between-session differences are large.
% Third, there are heavy spikes at the start and end of each session when
% the signal is whitened which can be avoided when the (whitened) baseline
% is subtracted.

Cheers
Joram

**Comment by FaxinZ** [comment]
Dear Joram,

Really thank you for your patient reply! That really helps.
And yes, the first model (M1) is nested within the second model(M2), and then I simply subtract the 'MA_GoF_R2.nii' of the M1 from that of M2 to get the difference image, but some voxels get negative value, which seems a bit weird...
I believe I should check my code and try once more, and thanks again!

Best,
Faxin

**Comment by JoramSoch** [comment]
OK, thanks. Let me know, if there are still problems after debugging, and feel free to send "SPM.mat" and "R2.nii" of the two models for closer inspection.
